### ISSUE TITLE
[Programme] Taille du PDF

### ISSUE THREAD

**Issue by vogloblinsky** [breizhcamp/website-legacy#100]
Bonjour,

J'ai essayé d'imprimer le PDF du programme mais je vois dans le code du template que c'est configuré pour du A6 ?

C'est volontaire pour glisser ça dans les portes badges ?

Merci

**Comment by lucsorel** [comment]
bonjour Vincent,

Oui, c'est le support que nous utilisons pour les porte-badges. Il y a sans doute la possibilité de l'imprimer sur un support plus grand en demandant d'adapter la taille du contenu à la taille de la page.

Peux-tu spécifier un peu plus l'objet de cette issue, s'il te plaît ?

**Comment by vogloblinsky** [comment]
Ok je clôture l'issue, j'ai réussi à l'imprimer sur du A4 en précisant en entrée le format A6.
