### ISSUE TITLE
Extra coma after alone speaker name

### ISSUE THREAD

**Issue by artentica** [breizhcamp/website-legacy#49]
![image](https://user-images.githubusercontent.com/6542338/53018662-3a816800-3453-11e9-8798-76f77d633552.png)

Quand il n'y a qu'un seul speaker une virgule est constamment ajoutée.
Je n'ai pas trouvé ou corriger ça  (mais je vais regarder ce soir)

EDIT: provient probablement de là => https://github.com/breizhcamp/website/blob/a1c012692d23ca0161b21b711894b05b7159e01e/bin/extract-talks-json.jq#L11

**Comment by rikles** [comment]
Bonjour,
Merci pour le retour,
Ça ne vient pas du fichier indiqué, mais je suis en train de regarder le pb...

**Comment by artentica** [comment]
Le truc c'est que si on reçoit ["toto titi, "] on aura bien => ["toto titi"]
Cependant si on a ["toto titi,"] on aura  ["toto titi,"]
Si ça vient bien de là où je pense (oui j'insiste sans vraiment savoir faut pas trop m'en vouloir) il faudrait faire: `.speakers | rtrimstr(" ")  | rtrimstr(",") ` supprime le potentiel espace en trop puis la virgule non voulue.
Je peux faire la PR si c'est bien ça.

**Comment by rikles** [comment]
C'est corrigé ;-)
