### ISSUE TITLE
La ligne 41ex n'existe plus

### ISSUE THREAD

**Issue by gardouille** [breizhcamp/website-legacy#76]
Listée dans les solutions de [Comment me rendre au BreizhCamp ?](https://www.breizhcamp.org/faq/#comment-me-rendre-au-breizhcamp), la ligne [41ex du star n'existe plus](https://www.star.fr/se-deplacer/bus-metro) depuis l'arrivée du métro ;)
https://github.com/breizhcamp/website/blob/697cef746ded7cf937f15ccd26f764b7391fa1b9/content/faq/_index.md?plain=1#L38

**Comment by alexthomazo** [comment]
C'est corrigé, merci 🙂
